Added functionalities
Othniel2471/awesome-books pull request #2
Opened 2023-05-29 14:01 UTC by Othniel2471

### In this branch my partner and I:

- Added a function to add new book objects to populate the books array.
- Added a delete function to remove books.
- Added the local storage function.

2023-05-29 14:19 UTC, Strangeal reviewed
Hi @Othniel2471, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional `README`.  Kindly create a professional `README` as it's essential to document your project so your users can have an insight into what your project details. To create a professional `README` please use the [README TEMPLATE](https://github.com/microverseinc/readme-template) provided by microverse.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-29 15:07 UTC, emmiiorji requested changes
Hi Team, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Adding and removing books work as expected
- Using an array to hold books is good


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-29 15:07 UTC, emmiiorji commented on assets/js/index.js
> +});
You have done great at saving to the local storage. I think that it'll be better adding an item to the books collection and then saving the collection to the local storage instead of saving each item differently.

2023-05-29 15:07 UTC, emmiiorji commented on assets/js/index.js
> +
Kindly utilize the saved items in the local storage such that reloading the page gets the saved collection and displays them.

2023-05-29 15:07 UTC, emmiiorji commented on assets/js/index.js
> +    }
As [required](https://github.com/microverseinc/curriculum-javascript/blob/88159c024f2d8d80ebfbf40d42be4c9797431e67/books/m1_plain_js_objects.md?plain=1#L43), kindly ensure that the local storage gets updated when I delete a book.

2023-05-29 15:07 UTC, emmiiorji commented on assets/js/index.js
> +};
As [required](https://github.com/microverseinc/curriculum-javascript/blob/88159c024f2d8d80ebfbf40d42be4c9797431e67/books/m1_plain_js_objects.md?plain=1#L43), kindly ensure that the local storage gets updated when I add a book.

2023-05-29 18:56 UTC, Davidosky007 approved these changes
Hi @Othniel2471 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
*  Objects in JavaScript created 👍 
*  Properties and methods of JavaScript objects accessed properly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 14:25 UTC, rloterh reviewed
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that appears already approved. If this is a new activity/sub-module of a project, kindly create a new Pull Request for the same and then resubmit for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-30 14:29 UTC, closed without merging